{"uuid": "f6fe25f1-8864-4ca4-a78c-af7df30ab337", "children": ["3702a5c1-cef0-4410-a389-b4b9e44855e5"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa109b5ac40>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/conftest.py\", line 60, in browser\n    driver = webdriver.Remote(\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 826, in urlopen\n    return self.urlopen(\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 826, in urlopen\n    return self.urlopen(\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 826, in urlopen\n    return self.urlopen(\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 798, in urlopen\n    retries = retries.increment(\n  File \"/home/alisapokormlyak/Desktop/otus_project/project/venv/lib/python3.9/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1691658220127, "stop": 1691658220128}], "start": 1691658220127, "stop": 1691658220273}